"""secound

Revision ID: 688c7fd10cb3
Revises: d4a27cc33472
Create Date: 2021-03-19 22:05:46.923186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688c7fd10cb3'
down_revision = 'd4a27cc33472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_unique_constraint(None, 'user', ['_phone_number'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
